# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications.proto

require "google/protobuf"

require "google/protobuf/empty_pb"

descriptor_data = "\n\x13notifications.proto\x12\rnotifications\x1a\x1bgoogle/protobuf/empty.proto\"K\n\x13NotificationRequest\x12\x0e\n\x06userId\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0bmessageType\x18\x03 \x01(\t2e\n\x13NotificationService\x12N\n\x10SendNotification\x12\".notifications.NotificationRequest\x1a\x16.google.protobuf.Emptyb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Notifications
  NotificationRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("notifications.NotificationRequest").msgclass
end
