# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: notifications.proto for package 'notifications'

require "grpc"
require_relative "notifications_pb"

module Notifications
  module NotificationService
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "notifications.NotificationService"

      rpc :SendNotification, ::Notifications::NotificationRequest, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
